### ISSUE TITLE
Import Error when running test_detection.py

### ISSUE THREAD

**Issue by sakinachou** [PuchatekwSzortach/face_detection#1] opened 2017-05-10 15:04 UTC
Hi,
I'm a newbie in python. Could you explain how to run your code please?  
I installed all dependencies (OpenCv3, numpy, pytest, mock) to run test_detection.py, but I've this error:

Traceback (most recent call last):
  File "test_detection.py", line 11, in <module>
    import face.detection
ImportError: No module named face.detection

How can I fix it? 

Thanks

**Comment by PuchatekwSzortach** [comment] 2017-05-11 01:52
Based on the scant description you provided, I would assume one of the following is the problem:
- you are not running code from project directory
- (more likely) you haven't set your PYTHONPATH environment variable to current directory (`export PYTHONPATH="."`)

**Comment by sakinachou** [comment] 2017-05-11 08:58
Thanks for the answer. 
1- I must set PYTHONPATH at the root of the project, right?
2- I have a question about the requirements, too: Which version of python and openCV do you use?
       - If I use python 2.7, I have an issue with methods super() in class creation, which belongs to python3+
       - If I use python 3.6,  I have an issue with the import of cv2 library; but cv2 is specific to python2 from what I know

3- I had to add "__init__.py" file in "face" repository so that it could be considered as a module. 

4- Could you, please, give a script that shows how to use your library to get a face detection (in order to obtain, for exampe, the result available in "images" repository) 

Thank you very much for your time :)

**Comment by PuchatekwSzortach** [comment] 2017-05-11 09:03
1. You need to set PYTHONPATH in your bash profile file.
2. This project uses Python 3. cv2 isn't Python 2 specific, but Python 3.6 is fairy new and OpenCV doesn't provide binaries for it right now. Try going with Python 3.4 or 3.5.
3. Hmm, this one is strange, there should be an `__init__.py` file in there already.
4. I already provided one, have a look at `scripts/visualization.py`.

**Comment by PuchatekwSzortach** [comment] 2017-05-17 14:39
@sakinachou Do you still need any help? If not I'll close this issue.

**Comment by ghost** [comment] 2017-05-17 16:49
Hi PuchatekwSzortach maybe sakinachou does not need help anymore, but I do.
I have the same problem, using Python 3.6.

```
Traceback (most recent call last):
File "C:\face_detection-master\scripts\download_data.py", line 5, in <module> 
    import face.detection
ModuleNotFoundError: No module named face
```

I created a new environment variable PYTHONPATH and set to C:\Python36. My system PATH value as well.
The project is located in C:\face_detection-master, and this folder is a PATH directory too.
OpenCV 3.2 successful when imported, same for numpy.

Where do you think the problem is?
Thanks

**Comment by PuchatekwSzortach** [comment] 2017-05-18 00:50
@edupignatelli `PYTHONPATH` variable isn't for pointing at Python executable, that's what `PATH` is used for. `PYTHONPATH` specifies directories in which Python should look for scripts you wish to execute. Usually it's best to set it to current directory `"."`, so that Python will look for scripts relative to directory from which you called them. This way if you call `python ./scripts/download_data.py` from `C:\face_detection-master`, appropriate script will be found.

**Comment by sakinachou** [comment] 2017-05-18 08:50
I still need help, yes^^.

I set PYTHONPATH to the directory where there are the scripts, and I don't have "import error" anymore, but it is still writing in "Traceback"

```
Traceback (most recent call last):
  File "./scripts/visualization.py", line 14, in <module>
    import face.utilities
```
Don't know if it is really a problem.

Plus, I still have a problem with cv2. I added the path "../python2.7/dist-packages" which contains cv2.so with `sys.path.insert` because "../python3.4/dist-packages" doesn't contain it. So, now, I don't have "no module named cv2" error anymore, but I have:
``` 
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define init function (PyInit_cv2)

Thanks for your help
```

**Comment by PuchatekwSzortach** [comment] 2017-05-18 09:00
@sakinachou As for first import issue - please pull latest commit `d2b508d ` and if problem still occurs, please report your input and full trackback.

As for OpenCV -  it looks like you are trying to use Python 3.4 OpenCV compiled for Python 2.7. You can't freely mix Python 2.7 libs with Python 3 interpreter. This is a problem irrelevant to my code and I recommend you look for solutions on Google. A good place to start would be to install Python and relevant OpenCV with Anaconda, then check if running `import cv2` in Ipython succeeds.

**Comment by ghost** [comment] 2017-05-18 10:40
I figured it out, if this can help.

Installed Python 3.5.3.
Downloaded the following wheels from here and installed with pip (python -m pip install "filename"): http://www.lfd.uci.edu/~gohlke/pythonlibs/
- Keras-2.0.4-py2.py3-none-any;
- numpy-1.13.0rc1+mkl-cp35-cp35m-win_amd64;
- tensorflow_gpu-1.1.0-cp35-cp35m-win_amd64;
- tensorflow-1.1.0-cp35-cp35m-win_amd64;
- opencv_python-3.2.0-cp35-cp35m-win_amd64;
- Shapely-1.5.17-cp35-cp35m-win_amd64;
- scipy-0.19.0-cp35-cp35m-win_amd64;

Put the files in the referenced python PATH directory to make it find them.

Anyway, I have now more problems:

1. When running download_data.py it raises 
`HTTP Error 429: Too Many Requests`

2. And when running train_model.py instead raises
```
 File "C:\Users\epignatel\Documents\PythonProjects\face_detection-master\scripts\train_model.py", line 8, in <module>
   import keras
 File "C:\Python35\lib\site-packages\keras\__init__.py", line 3, in <module>
   from . import activations
 File "C:\Python35\lib\site-packages\keras\activations.py", line 4, in <module>
   from . import backend as K
 File "C:\Python35\lib\site-packages\keras\backend\__init__.py", line 73, in <module>
   from .tensorflow_backend import *
 File "C:\Python35\lib\site-packages\keras\backend\tensorflow_backend.py", line 1, in <module>
   import tensorflow as tf
 File "C:\Python35\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
   from tensorflow.python import *
 File "C:\Python35\lib\site-packages\tensorflow\python\__init__.py", line 51, in <module>
   from tensorflow.python import pywrap_tensorflow
 File "C:\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 52, in <module>
   raise ImportError(msg)
mportError: Traceback (most recent call last):
 File "C:\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
   from tensorflow.python.pywrap_tensorflow_internal import *
 File "C:\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 35, in <module>
   _pywrap_tensorflow_internal = swig_import_helper()
 File "C:\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 30, in swig_import_helper
   _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
 File "C:\Python35\lib\imp.py", line 242, in load_module
   return load_dynamic(name, filename, file)
 File "C:\Python35\lib\imp.py", line 342, in load_dynamic
   return _load(spec)
mportError: DLL load failed: The specified module could not be found.

See https://www.tensorflow.org/install/install_sources#common_installation_problems for some common reasons and solutions.
```

Seems like it fails to load keras and tensorflow. Maybe this can help others.

**Comment by PuchatekwSzortach** [comment] 2017-05-18 10:59
@edupignatelli I suspect your Python installation and/or some libs aren't set up correctly. Just as to @sakinachou, I would recommend to install Python using Anaconda and then import a few modules and run some simple code from IPython interpreter to check everything really works.

**Comment by ghost** [comment] 2017-05-19 10:20
Thank you PuchatekwSzortach. Installing Python through anaconda maked it work.
I am still being rejected on the dropbox request, due to flooding I believe?
Would it be possible to access the resources in any other way?
Or maybe just see an example of the .txt file to understand the parsing logic?

**Comment by PuchatekwSzortach** [comment] 2017-05-19 10:36
@edupignatelli I tried accessing Celeb dataset over browser (you can google it up quickly) and it turns out Dropbox account on which it's stored was temporarily disabled due to creating too much traffic. Sorry, I can't help you with this, but you could reach out to data owners - I did in the past and they replied quickly.

**Comment by PuchatekwSzortach** [comment] 2017-05-19 10:53
@edupignatelli 
There are two txt files.  
1. File paths list with entries like:

    /some_path/data/faces/img_celeba/000001.jpg
    /some_path/data/faces/img_celeba/000002.jpg
    ...

2.  Bounding boxes file with entries like:

    10000
    image_id x_1 y_1 width height
    000001.jpg  95 71 226 313
    000002.jpg  72 94 221 306
    ...

where first line is the total number of images, second a simple cvs header, and following lines have format as described in second line.

These are then fed to generators, refer to `main()` function of `./scripts/train_model.py` for an example, where `training_image_paths_file` is the first file with fully qualified paths and `training_bounding_boxes_file` is the corresponding bounding boxes file.

**Comment by sakinachou** [comment] 2017-05-19 11:49
Thank you @PuchatekwSzortach , cv2 error disappear with anaconda.
@edupignatelli , which version of anaconda did you install? I installed the last one (for python3.6) because I can't find a way to choose the version I wish. (I followed this site: https://docs.continuum.io/anaconda/install-linux.html)
 But now, as @PuchatekwSzortach forsaw, I have compabilities issues with modules, like shapely.

**Comment by PuchatekwSzortach** [comment] 2017-05-19 11:53
@sakinachou Here are old Anaconda versions: https://repo.continuum.io/archive/index.html
Problem with shapely seems unlikely, what exactly was it?

**Comment by PuchatekwSzortach** [comment] 2017-05-19 11:58
@sakinachou Also note that what exact version of Anaconda you installed isn't too important, as you can create different environments with different Python versions which will automatically pull correct library versions. You can read up about Anaconda environments on its documentation page, it's quite thorough and easy to understand.

**Comment by sakinachou** [comment] 2017-05-19 15:10
Great! Thanks @PuchatekwSzortach it worked well to change version of Anaconda from 3.6 to 3.5 (python3.4 doesn't work with your code because we need tqdm and it's compatible for 3.5+).
But, did you guys have this error? when launching visualization.py 

```Using TensorFlow backend.
Traceback (most recent call last):
  File "scripts/visualization.py", line 121, in <module>
    main()
  File "scripts/visualization.py", line 116, in main
    log_face_detections(image_paths_file, logger)
  File "scripts/visualization.py", line 76, in log_face_detections
    model = face.models.get_pretrained_vgg_model(face.config.image_shape)
  File "/home/projet-d/Documents/tests_detect_track/testdeep_dense_YahooDetection/face/models.py", line 27, in get_pretrained_vgg_model
    x = keras.applications.VGG16(include_top=False, weights='imagenet')(input_layer)
  File "/home/projet-d/anaconda3/lib/python3.5/site-packages/keras/applications/vgg16.py", line 169, in VGG16
    model.load_weights(weights_path)
  File "/home/projet-d/anaconda3/lib/python3.5/site-packages/keras/engine/topology.py", line 2488, in load_weights
    raise ImportError('`load_weights` requires h5py.')
ImportError: `load_weights` requires h5py.
```
Although I have h5py installed:
```
# packages in environment at /home/projet-d/anaconda3:
#
h5py                      2.7.0               np112py35_0
```
(checked on the Internet for this error, they advise installing requirements --> Already have hdf5 and cython.) Hope it's a question relevant to your code

**Comment by PuchatekwSzortach** [comment] 2017-05-19 15:15
@sakinachou tqdm works on Python 3.4, I suspect you either didn't install it or have a directory containing some other Python coming in before your Anaconda in your path.

As for the import error this might be due to loading a weights file that isn't present on your system (since you likely didn't train a model yet), but more likely just at tqdm it's an indication you aren't actually running Python version you think you are. Double check output of your `python --version`, `which python`, `which pip`, as well as `__file__` attributes of a few modules imported with `ipython` for pointers. I suspect there is a directory including a different Python binary coming in before Anaconda directory in your PATH.

**Comment by PuchatekwSzortach** [comment] 2017-05-19 15:21
@sakinachou You could train a simple Keras model (on MNIST or whatever), save it and then try to load its weights to see if that works.

**Comment by ghost** [comment] 2017-05-22 09:00
Hi PuchatekwSzortach,
Thank you for the layout.
I got the access to the celebA dataset. Here is the link for future questions.
https://drive.google.com/drive/folders/0B7EVK8r0v71pWEZsZE9oNnFzTm8

The algorithm still fails downloading the package, so I am trying to tweak the code to yield from local data.
It stops while searching for "validation_image_paths" and related bb.
Could it be possible to know what information should this asset contain?

Thank you as always

**Comment by PuchatekwSzortach** [comment] 2017-05-22 09:08
@edupignatelli  Probably data is not saved where software expects it to be. Looking through `scripts/download_data.py` and `face/config.py` you can see paths to which data is downloaded. Depending on where you put the code on your hard drive, these might be actually unreachable (in short data is expected to be at `./../data/faces/` relative to code directory). Make sure what paths data is really put on and modify paths it is search at accordingly if necessary.

**Comment by sakinachou** [comment] 2017-05-22 14:50
Hi @PuchatekwSzortach ,
Here are the versions I have, but when I install ``pip install visual-logging`` with 3.5, I have errors (see above) so I had to add some python 3.4 to PYTHONPATH (no error of vlogging with python 3.4). 
```
File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1490028461908/work/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1490028461908/work/h5py/_objects.c:2804)
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open (/home/ilan/minonda/conda-bld/h5py_1490028461908/work/h5py/h5f.c:2123)
```

```
projet-d@projetd-VirtualBox:~$ pip -V
pip 9.0.1 from /home/projet-d/anaconda3/lib/python3.5/site-packages (python 3.5)
projet-d@projetd-VirtualBox:~$ python --version
Python 3.5.3 :: Continuum Analytics, Inc.
```
I don't know how to train a model :/ I think I will look for another code a bit easier for me, who don't know a lot about python and deep learning. ^^""

**Comment by PuchatekwSzortach** [comment] 2017-05-22 14:53
@sakinachou pip version of visual-logging seems to have a problem with Python 3, I recommend installing it from Github. To train a model just call `scripts/train_model.py`

**Comment by PuchatekwSzortach** [comment] 2017-05-22 15:14
@sakinachou BTW, aren't you using Miniconda, a minimalistic version of Anaconda, rather than full blown Anaconda by any chance? If so, you might have missing dependencies. I would recommend opting for a full Anaconda if possible.

**Comment by sakinachou** [comment] 2017-05-22 15:36
I'll try to install it with GitHub. I checked and I have Anaconda 3, not Miniconda ;) 
BTW, Where do I find ``training_image_paths.txt`` and ``training_bounding_boxes_list.txt`` and the same files on validation too?

**Comment by PuchatekwSzortach** [comment] 2017-05-23 01:21
@sakinachou Inside `./../data/faces/` folder, specified w.r.t. code directory. You can change this in `face/config.py`. All this information is right there in top level scripts, just read them.

**Comment by sakinachou** [comment] 2017-05-24 09:27
I understand that I have to change the paths to fit with my own tree, but ``training_image_paths.txt``, and other .txt files referenced in config.py, I don't see them anywhere, and I don't know what I'm suppose to put inside, if I have to create it.

**Comment by PuchatekwSzortach** [comment] 2017-05-24 10:26
@sakinachou These files are created by `scripts/download_data.py`. However this script will likely fail now, as Dropbox account it downloads data from has been temporarily disabled.

As for content of `training_image_paths.txt`, `training_bounding_boxes_list.txt` and friends, I described it a few comments above ( https://github.com/PuchatekwSzortach/face_detection/issues/1#issuecomment-302672676 )

**Comment by PuchatekwSzortach** [comment] 2017-05-28 03:56
@sakinachou, @edupignatelli  - Do you guys need any more help? If not, I'll soon close this issue.

**Comment by PuchatekwSzortach** [comment] 2017-06-05 12:32
Since I haven't heard from neither @sakinachou nor @edupignatelli for a while, I'm closing this issue.

**Closed as completed by PuchatekwSzortach** 2017-06-05 12:32 UTC
Labels: help wanted
